# Generated by Django 4.2.2 on 2023-07-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30)),
                ('r_name', models.CharField(max_length=30)),
                ('dst', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('cargo_type', models.CharField(max_length=25)),
                ('weight', models.IntegerField()),
                ('date', models.DateField()),
                ('ctno', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
