# Generated by Django 4.2.2 on 2023-07-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderno', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=30)),
                ('r_name', models.CharField(max_length=30)),
                ('dst', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('cargo_type', models.CharField(max_length=25)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('ctno', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
